invesalius/invesalius3

invesalius/gui/data_notebook.py
invesalius/gui/default_tasks.py
invesalius/gui/default_viewers.py
invesalius/gui/dialogs.py
invesalius/gui/frame.py
invesalius/gui/import_panel.py
invesalius/gui/task_exporter.py
invesalius/gui/task_importer.py
invesalius/gui/task_slice.py
invesalius/gui/task_surface.py
invesalius/invesalius.py

Fixed problems with sizers, colors ans panel sizes.
Created functions to calculate panel sizes inside foldpanelbar
Showing the left-down panel where masks and surfaces info are showed
applyied the patches from Olly Betts to run in wxpython3
The gradient widget is working
The comboboxes from mask properties are working now.
The problem was that combobox must not empty.
Surface task is working again
Putting combobox thresholds presets in a new line
putting the import pil inside a try except
expanding the label 'set predefined or manual threshold'
showing the buttons when importing a dicom
better layout to task_slice
the size of the data_notebook
the size of the buttons inside of data_notebook
the size of the volume viewer icons
solved the problem with position of statusbar using idle event …

Adpated InVesalius to run in wxpython3

---

invesalius/data/measures.py
invesalius/data/styles.py
invesalius/data/viewer_slice.py
invesalius/gui/data_notebook.py
invesalius/utils.py

Support to Drag and drop to measures. It only works inside the slice viewer. The support to 3D viewer is more complicated, because the code to interact with this viewer is not well separated like in the slice viewer. In Slice viewer we have the concept of Styles class. Each Style class is responsible to one type of interaction. For instance, LinearMeasureInteractorStyle is responsible to linear measure interaction.
The measures are stored inside the class MeasureData. This class is a Singleton. This was needed because LinearMeasureInteractorStyle needs to access each measurement directly to know if an existing measure was clicked. It was not possible before, because the list of measures was not directly accessible from this class.
The idea of Adding and removing the actors is not more …

Drag and drop support to measures in slices

---

invesalius/data/viewer_volume.py
invesalius/gui/task_navigator.py

Activation/deactivation of external trigger allowed just when navigation is off.
Marker creation optimization. (using refresh instead render)

Avoided external trigger bugs

---

invesalius/data/trigger.py
invesalius/data/viewer_volume.py
invesalius/gui/task_navigator.py

When a markers is double-clicked in the list ctrl the marker in the volume starts to blink.
- To stops blink just press once at any place in the list ctrl 
It is possible now to select multiple markers in the list ctrl and remove all selected markers.
Trigger improvements
- Now Polhemus Stylus button creates markers inside the trigger thread. Avoiding navigation freezing.

Markers manipulation improvement

---

invesalius/control.py

Running Invesalius via CLI to export DICOM/Bitmap to 3D (STL, OBJ et al) generated stretched 3Ds while in GUI everything was fine. The bug was present in _OpenBitmapFiles()_ and _OpenDicomGroup()_, I'll refer to the latter method: after calculating resolution_percentage (**line 800**) when in GUI _xyspacing_ was adjusted accordingly (**line 814**) but, since via CLI the if condition (**line 802**) it's not met, this caused discrepancies in the 3d dimensions. 
This subtle bug was probably caused by an error in indentation, moving **line 814** outside of **line 802** if, fixed the issue in my scenarios and should be sufficient.

Fix xyspacing in invesalius/control.py

---

invesalius/control.py
invesalius/data/surface.py
invesalius/data/trackers.py
invesalius/gui/data_notebook.py
invesalius/gui/dialogs.py
invesalius/project.py

Tool to transform an imported object to InVesalius coordinate system. 
-works only with nifiti, rec/par and analyze images
-affine matrix is saved at main.plist of inv project
-scalarvisibility set as on for vtp files (feature for DTI import)
TODO: 
-choose the coord system of the export surface
-Set scalarvisibilityon when an inv project is opened

Transform surface physical into inv coord system

---

invesalius/data/viewer_slice.py
invesalius/gui/dialogs.py

While using the tool Go To Slice with the slices' cross navigation activated, neither the focal point of the cross, or the neuronavigation coords, or  the 3D viewer were being updated. This changes have fixed that.

Fixing the cross focal point update in Go To Slice tool

---

invesalius/data/viewer_volume.py

Not used by InVesalius, but useful when wanting to have the
information about coil being at the target or not outside
InVesalius.

ADD: Send 'Coil at target' message

---

invesalius/data/viewer_volume.py
invesalius/gui/default_viewers.py
invesalius/gui/task_navigator.py

Most of these changes refactor and rearrange the internal events so that when setting markers
using 'Set markers' event, one of the markers can be set as the target, and InVesalius then
correctly updates all the internal variables needed when a target is set.

Allow setting markers remotely by using 'Set markers' event

---

invesalius/constants.py
invesalius/gui/task_navigator.py

Refactoring related to registering image and tracker fiducials. The changes:
- Use events 'Set tracker fiducial' and 'Set image fiducial' called by the UI to create a cleaner separation between the UI and the logic.
- Make fiducial definitions in constants.py clearer and easier to use
- Decouple fiducial name (e.g. 'LE') from the marker and button names ('LEI' or 'LET'), allowing a cleaner interface to 'Set tracker fiducial' and 'Set image fiducial' events.

Fiducial-related refactoring

---

invesalius/gui/task_navigator.py

FIX: Neuronavigation not working when target not defined
- self.target was initialized in the wrong class, causing the neuronavigation
to not work when a target is not defined. Move the initialization to the
correct class.
- Due to a minor mistake in previous merge conflict resolution, UpdateTarget
function was defined twice. Remove the redundant definition.

FIX: Neuronavigation not working when target not defined

---

invesalius/data/coregistration.py

- Check that the target is not None before transforming it in CoordinateCorregistrate class.

FIX: A bug in navigation without a target

---

app.py

This reverts commit 30ae50b1b29bb0d9c331971f0190fe7b5332e12b.
See #247 for more information: apparently this is not the correct fix, but it still causes InVesalius to not work with wxPython 4.0.6, as that version does not have the ResetLocale function. (I'm not sure if 4.0.6 should be supported in the first place, but it's probably better to stay conservative until the correct fix is found.)

Revert "FIX: Locale problem crashing with Windows 10 and certain locales (#283)"

---

app.py
invesalius/constants.py
invesalius/gui/task_navigator.py

Tested a couple of functions after this change, and they seemed to work without error messages or warnings in the console:
- Opening a project and selecting a tracker
- Selecting another tracker when one tracker is already selected
- Selecting a non-working tracker
- Opening another project when one project is already opened (closing the connection to the tracker)
- Closing InVesalius
I also tentatively fixed my GitHub email address so the merge commit shouldn't show two separate authors for the change anymore -- let's see if it works.

MOD: Remove 'Disconnect tracker' option from tracker dropdown menu

---

invesalius/gui/task_navigator.py

Thanks to @sotodela for the fix! I was apparently confused of what `self.trk_init[0]` is used for.

FIX: Disconnecting tracker when a real tracker is connected

---

invesalius/data/serial_port_connection.py
invesalius/gui/task_navigator.py

- The correct way to ask if serial port is enabled is to use
SerialPortEnabled function in Navigation class.
- While at it, remove the unused Enabled function from
SerialPortConnection class.

FIX: Bug in StopNavigation, causing error if serial port not enabled

---

invesalius/data/coordinates.py
invesalius/data/viewer_volume.py

-Modify visibility of red ball when peel is loaded. Ball is not visible when the coil projections hits the peel. 
-Modify visibility of x, y, z line actors to not be visible
-Modify visibility of torus and arrow actors when adding the object (coil) to not be visible.

Remove ball when coil is projected

---

invesalius/data/viewer_volume.py
invesalius/gui/dialogs.py
invesalius/gui/task_navigator.py

- Previously, coil without handle was used to mark the target only if
object calibration had not been done yet. After object calibration
was done, the variable polydata stored the coil mesh that was selected
by the user when doing the calibration, and hence that coil mesh
(typically containing the handle) was used to mark the target.
- Change the logic to follow these rules:
* When the default coil is selected in object calibration, use the
default coil with a handle to mark the coil location, and default
coil without a handle to mark the target.
* When object calibration is not yet done, use default coil without
a handle to mark the target.
* When a custom coil is selected in object calibration, use the custom
coil to mark both the coil location and the target, regardless of if
the mesh …

MOD: Change logic for when to use coil without handle to mark the target

---

invesalius/data/coregistration.py
invesalius/gui/dialogs.py
invesalius/gui/task_navigator.py

- Rather than a property of the tracker object, it should be passed
to the tracker object from outside, since it depends on the context.
For example, during the navigation, we might want to use a reference
mode that is different from what we use during the object calibration.
Therefore, move the reference mode that is used during navigation into
Navigation class.

MOD: Move tracker reference mode used in navigation into Navigation class

---

invesalius/data/coregistration.py

- The angles returned by translations.decompose_matrix use the
axe order 'sxyz'. It is also the default for translations.euler_from_matrix,
although that function allows changing the order.
Therefore, change to using euler_from_matrix, and instead of defaulting to the
axe order 'sxyz', be explicit about it to make it easier to notice any bugs.

CLP: Be explicit about the order of axes when computing Euler angles

---

invesalius/gui/task_navigator.py

* current_coord is not actually used by Navigator class, in which
it resided previously. Instead, it is used by NeuroNavigationPanel
when an image fiducial is unselected (the button for selecting
the image fiducial is pressed twice). Previously, unselecting
an image fiducial caused a crash due to not having current_coord
variable in NeuroNavigationPanel. This patch moves it there to
fix the bug.

FIX: Bug in task navigator: unselecting image fiducial does not work

---

invesalius/data/bases.py

* Due to a previous clean-up, r_s0_raw was not computed anymore
in object_registration function. However, it is needed as one
of the return values of the function, therefore add it back.

FIX: Bug in object registration, causing navigation to not work

---

invesalius/gui/task_navigator.py

Namely, do not attempt to add or remove pedal callbacks if the
PedalConnection object is not available (e.g., due to missing
Python MIDI libraries).

FIX: Bug in setting tracker fiducials

---

invesalius/constants.py
invesalius/gui/dialogs.py
invesalius/gui/task_navigator.py

* Add OBJECT_FIDUCIALS dict to constants.py, replacing BTNS_OBJ
and TIPS_OBJ, and facilitating cleaning up the code.
* Pass PedalConnection object to ObjectCalibrationDialog so that
the pedal can be used for object calibration.
* Copy and slightly adapt the code that was used to set tracker
fiducials using pedal (in OnTrackerFiducials in NeuronavigationPanel
class) to do the same for object fiducials. Mark code duplication with
TODO comment for later clean-up.
* Rename a function (OnGetObjectFiducials -> OnObjectFiducialButton),
and rename a few variables (e.g., btn_id -> fiducial_index).

MOD: Allow setting object fiducials using pedal

---

invesalius/gui/task_navigator.py

More cleanup of the markers' code. Support for the old export format (.mks) dropped.

Markers code cleanup

---

invesalius/constants.py
invesalius/data/serial_port_connection.py
invesalius/data/trackers.py
invesalius/gui/dialogs.py
invesalius/gui/task_navigator.py
invesalius/navigation/navigation.py

Other changes:
- Disallow not selecting COM port in COM port selection dialog by
defaulting to the first COM port in the list. Previously, it was
possible to pass an empty string as the COM port by not making
the selection.
- When the "Serial port" checkbox is pressed and the user presses
"Cancel" in the dialog that is opened, uncheck the "Serial port" checkbox
instead of keeping it checked.
- Be explicit about if the serial port is in use or not, instead of inferring
it from the COM port variable being set or not.
- Pass the serial port parameters (COM port, baud rate) directly to the
Navigation class, instead of passing them through NeuronavigationPanel.
- Minor improvements to style and naming of the variables.

MOD: Allow selecting baud rate for serial port communication

---

invesalius/gui/dialogs.py

Removes a minus multiplication in the dialog for object registration that was causing all object registrations to be wrong.
The fix was tested with Polaris and Optitrack cameras.

FIX: Coil registration had wrong minus in Z coord

---

invesalius/data/viewer_volume.py

self.Refresh() is not updating the 3D view in unix. 
self.interactor.Render() is slower than Refresh() thats why I created the condition.

FIX: updates render with refresh only in win

---

invesalius/data/viewer_volume.py
invesalius/gui/task_navigator.py
invesalius/navigation/navigation.py
invesalius/net/neuronavigation_api.py

Adds neuronavigation_api integration with setting marker orientation. task_navigator also now subscribes to set markers so its marker state stays in sync with viewer_volume marker state. In addition, now viewer_volume correctly sets orientation when creating markers that already have an orientation set.

Integrate orientation

---

invesalius/data/imagedata_utils.py

Fix the import of MRI images with float64 (possibly any other float). Now, when importing a NIFTI file, we check if the range of pixel values exceed the limit of uint16 precision. If it exceeds, we rescale the pixel range to allow proper conversion to int16. Tested with a three different MRIs from different scanners.

FIX: Import MRI with float64 by rescaling pixel values

---

invesalius/data/coregistration.py
invesalius/data/viewer_volume.py
invesalius/gui/task_navigator.py
invesalius/navigation/navigation.py
invesalius/net/remote_control.py

- Add the feature to set a robot target, using InVesalius, and send it to the robotic positioning
- Fix the distance to target estimation, instead of using the absolute subtraction, it's using the relative distance between the actual coil position and the targe `m_relative_target = np.linalg.inv(m_target) @ m_img`

ADD: Targeting robot with neuronavigation

---

invesalius/data/cursor_actors.py
invesalius/data/styles.py
invesalius/gui/task_slice.py
invesalius/gui/widgets/inv_spinctrl.py

Allows the user to set the unit (milimeters (mm), micrometer (µm) and px (pixels)) to the manual edition and watershed brush. Fixes #493

Pixel size unit

---

invesalius/data/trackers.py

I tested on Windows, does not work with only trck_init = pypolaris()

FIX: Fix initializing tracker sintax

---

invesalius/data/trackers.py

The variable is being assigned to itself, which is redundant and unnecessary. Since no modifications are being made to the variable, we can safely remove this assignment operation.

Avoid assigning a variable to its own value

---

invesalius/constants.py
invesalius/gui/dialogs.py

- New NDI Vega cameras are connected via IP.
- Removed CB_READONLY to enable the user to enter the IP or the COM port.

ADD: append NDI IP into combo box of NDI settings

---

invesalius/gui/task_navigator.py
invesalius/navigation/navigation.py

Object registration data now stored only in _navigation.py_ instead of being additionally stored in _task_navigator.py_. Methods in _task_navigator.py_ now use the object registration data stored in _navigation.py_. #612
This should also fix #575.

Object registration refactor

---

invesalius/data/viewer_volume.py
invesalius/gui/dialogs.py
invesalius/math_utils.py

inner1d is being [deprecated](https://github.com/numpy/numpy/blob/5047644af5fc65830fdadcf930695d4a941448c8/doc/source/release/1.15.0-notes.rst#deprecations). I tried with numpy 1.25 and it's not even importing:
```
In [1]: from numpy.core.umath_tests import inner1d
<ipython-input-1-cbece234166d>:1: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
from numpy.core.umath_tests import inner1d
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: The new DType API is currently in an exploratory phase and should NOT be used for production code.  Expect modifications and crashes!  To …
```

implements inner1d because the numpy one is being deprecated

---

invesalius/data/styles.py
invesalius/data/styles_3d.py
invesalius/data/viewer_slice.py
invesalius/data/viewer_volume.py
invesalius/gui/frame.py
invesalius/gui/task_navigator.py

Removed the _'Set cross visibility'_-messages in closing the project and changing the tool in favour of _'Enable style'_-messages, which have previously been used elsewhere in the invesalius code. 
The visibility of the ball reference on the 3D-surface is now controlled in the _SetUp_ and _CleanUp_ functions in _styles_3d.py_ instead of directly subscribing to _'Enable style'_. This is similar to how the visibility of the cross slices is controlled in _styles.py_.
Tracts are no longer removed when deselecting the cross tool.
Reduced console spam.
Fixes #216 resolves #618 resolves #620

Improve showing/hiding the slices' cross intersection tool

---

invesalius/data/viewer_volume.py
invesalius/gui/default_viewers.py
invesalius/gui/task_navigator.py

Target mode no longer requires coil to be shown.
Orange coil for targeting now also hidden with the show-coil checkbox
Resolve #628

Improve showing the coil and target mode

---

invesalius/gui/task_navigator.py

Now calls `MarkersPanel.SaveState()` when creating a marker using the `'Create marker'`-message.
Fixes #633

Markers saved after creating marker using 'Create marker'-message

---

invesalius/data/slice_.py
invesalius/data/surface.py
invesalius/data/viewer_volume.py
invesalius/gui/data_notebook.py
invesalius/gui/dialogs.py
invesalius/gui/task_exporter.py

New feature to export 3D surfaces in world/scanner space.
Enhanced importing 3D surfaces: checkbox to import in world space, checked by default.
Resolve #382

Export 3D surfaces in world space

---

invesalius/constants.py
invesalius/gui/dialogs.py
invesalius/gui/task_exporter.py
invesalius/gui/task_navigator.py

Changes to GUI used for importing/exporting 3D surfaces with a defined affine and when loading markers from file.

Replace FileDialogCustomizeHook uses with another dialog type

---

invesalius/data/slice_.py
invesalius/data/surface.py
invesalius/gui/dialogs.py
invesalius/gui/task_surface.py

Fix 3 bugs with surface and mask color management and wx controls
1. wx color buttons require integers and float were given, making all color buttons white
2. wx gradient methods to set min and max values were updated, as they were raising errors due to deprecated use of methods
3. remove_non_visible_faces plugin was raising an error when the color of the surface was changed before applying the plugin due to the variable having 4 values while the method expected 3

Fix color management with wxPython color buttons and surface

---

app.py

So that when calling InVesalius's main function from another Python script without command-line arguments, remote-host parameter can still be set.

ADD: Allow overriding remote-host command-line argument

---

invesalius/gui/task_navigator.py

If target mode is on, and a new target is set, it turns to false. This pull request fixes that

FIX: target toggle button update

---

invesalius/data/mask.py
invesalius/data/polydata_utils.py
invesalius/data/viewer_volume.py
invesalius/gui/frame.py
invesalius/presets.py
invesalius/utils.py

- The function `debug()` now prints only with the `--debug`-argument.
- Remove the following clutter from the console when starting invesalius:
- wxPyDeprecationWarning from wx.GetDefaultPyEncoding()
- prints from UpdateThresholdModes()
- prints of full vtk actor data in LoadActor()
- Fix mask density measure dialog box not working on macOS as it would on other operating systems.

Console cleanup and mask density measure ui fix

---

invesalius/data/imagedata_utils.py
invesalius/data/mask.py
invesalius/data/slice_.py
invesalius/data/styles.py
invesalius/data/surface.py
invesalius/data/surface_process.py
invesalius/project.py
invesalius/reader/bitmap_reader.py
invesalius/segmentation/deep_learning/segment.py

While triaging your project, our bug fixing tool generated the following message(s)-
> In file(s): [mask.py](https://github.com/invesalius/invesalius3/blob/master/invesalius/data/mask.py), [slice_.py](https://github.com/invesalius/invesalius3/blob/master/invesalius/data/slice_.py), [styles.py](https://github.com/invesalius/invesalius3/tree/master/invesalius/data/styles.py), [surface.py](https://github.com/invesalius/invesalius3/tree/master/invesalius/data/surface.py), [imagedata_utils.py](https://github.com/invesalius/invesalius3/tree/master/invesalius/data/imagedata_utils.py), [surface_process.py](https://github.com/invesalius/invesalius3/tree/master/invesalius/data/surface_process.py#L81), [bitmap_reader.py](https://github.com/invesalius/invesalius3/tree/master/invesalius/reader/bitmap_r …

Replaced `mktemp` with `mkstemp`

---

invesalius/gui/default_tasks.py

Data notebook minimal size now updates when collapsing/expanding the fold panel bar.
Resolve #682

FIX: Data notebook covers content while folded

---

invesalius/data/surface.py

Fix errors when exporting meshes that are in stl format. Remove in the name of the file the format and add .bin.

Fix export meshes for efield

---

invesalius/gui/default_tasks.py
invesalius/gui/task_navigator.py

Tweaks:
- Removed restriction on entering navigation panel without completing coregistration.
- Data notebook now unfolded by default.

HOTFIX: Load image fiducials from file

---

invesalius/data/viewer_slice.py
invesalius/data/viewer_volume.py
invesalius/gui/frame.py

The ruler update canvas was affecting the navigation performance. Now, if the navigation is on, the canvas updates only in the navigation loop.
Also, the ruler was set as disabled by default.

Improve navigation performance slice

---

invesalius/gui/task_tractography.py

Fix a small issue that prevents loading files for tractography on Mac by applying the correct encoding of filepaths from constants.
Extra comments removed.

FIX: Encoding file paths for tractography

---

invesalius/gui/task_efield.py

Modify as default plotting vectors. On the current E-field application, mTMS is not implemented for the condition where the vectors are not plotted, nor is the modification of dI/dt implemented.
In the future, it will be modified for conditions without max and centroid arrow locations for these conditions.

MOD: Remove check box for ploting vectors

---

invesalius/data/brainmesh_handler.py

Images acquired with a 7T MRI scanner typically have a spacing different from 1. When importing the tractography mask with this non-unit spacing, an offset occurs. Therefore, this correction involves multiplying the affine matrix by the appropriate spacing factor to align the images accurately

ADD tractografy mask position correction

---

invesalius/data/viewer_slice.py

When clicking on one slice panel with the cross function enabled, the other two slices were not updated until a second click was made. This fix this issue by rendering whenever the navigation is off. 
Important! Cannot have the rendering during navigation as it will slow down due to high computational load.

FIX: Slices failed to update when using the cross function

---

invesalius/data/brainmesh_handler.py

The fix applied by @LucasBetioli123 in #722 was still missing the (-1) applied to compensate for the origin translation. I renamed and commented his fixed to match what was applied for instance in the navigation.py module in StartNavigation.
Please test this PR with a non-unitary pixel spacing mask. Here with a unitary pixel spacing it works fine.

FIX: Add pixel shift to coordinate transformation in brain peeling mask

---

invesalius/net/pedal_connection.py

Catch keystroke pedal -related KeyError when trying to stop navigation without having started it first. This happens e.g. when loading a new project on top of an existing one.
Fixes #710

FIX: Closing project with keystroke pedal enabled

---

invesalius/gui/task_fmrisupport.py
invesalius/gui/widgets/gradient.py

- Refactor fMRI task_bar and gradient creation
- Removed transparency of gradient in fMRI
- Update colormap list
- Rescale images and convert to 8-bit integer values before applying colormap. This allows importing images with negative and decimal values (e.g., correlations) and t-statistics.

ENH: Support negative and decimal values in images and masks in fMRI colormaps

---

invesalius/data/mask.py

Clean error message on deleting a mask loaded from a project file. Error was introduced in #679, and is caused by the cleanup code attempting to delete a file through a file descriptor that doesn't exist.
Resolve #728

CLN: Error on deleting mask

---

invesalius/data/viewer_volume.py

Custom coil models could cause target guide models to overlap and cover content.

FIX: Always use default coil for creating target guides

---

invesalius/control.py

Define window width and window level based on 2-98 percentiles saturates the high pixel intensities that usually cause the image to and makes the brightness and contrast more similar across different types of scanners.
This fixes #745 the visualization issue only for MRIs imported with NIfTI, but not with DICOM.
Tested with 3 different MRIs that were previously being visualized very dark in InVesalius.

Fix mri brightness contrast

---

invesalius/navigation/robot.py

Added field self.target to __init__() in Robot class.
Fixes error message when starting navigation without having set a target before.

FIX: AttributeError when starting navigation

---

invesalius/gui/task_navigator.py

In MacOS it was not possible to right click the items of the Markers table due to an error in setting the menu id to 0.
Tested in MacOS M2 Sonoma and Windows 10 64.

FIX: Error in MacOS for ID 0 in right click of Markers Menu Item

---

environment.yml
invesalius_cy/cy_mesh.pyx
invesalius_cy/floodfill.pyx
invesalius_cy/interpolation.pxd
invesalius_cy/interpolation.pyx
invesalius_cy/transforms.pyx
requirements.txt

* Updated cython to 3.0.10 
* Added noexcept to transforms, cy_mesh, interpolation and floodfill
* reorientation is faster now

Update cython and fix reorientation slowness

---

invesalius/data/slice_.py

Reset Slice.to_show_aux when closing the project to prevent InVesalius from trying to load the discarded overlay.
Fixes #744

FIX: Change project after loading fMRI overlay

---

invesalius/gui/task_navigator.py

The marker's list height was too long for both small and bigger resolutions. Tested in MacOS at 1440p on a 27" monitor and 14" laptop monitor. 
This broken UI was also occurring in the mTMS lab with Windows on a 27" screen.
The fix is to adjust the increase of the list height less steep than the previous implementation.

FIX: Height of markers list was occluding robot buttons

---

invesalius/control.py
invesalius/data/visualization/coil_visualizer.py

Fixes issue [#764](https://github.com/invesalius/invesalius3/issues/764) on coil visibility.
- When opening a new project or starting a new session without recovering previous state, the coil is no longer immediately visible.
- Coil turns visible once tracker fiducials have been set and the coil is hidden when resetting tracker fiducials or changing the tracker.
- Loading a new project resets the tracker fiducials which in turn hides the coil until tracker fiducials are set.

FIX: Coil visibility issue #764

---

pyproject.toml

Setuptools needs name, version and packages in pyproject.toml to compile cython sources. Also added description, license, readme, keywords.

Added needed information to pyproject.toml to make setuptools happy to compile invesalius_cy

---

invesalius/data/imagedata_utils.py
invesalius/gui/dialogs.py
invesalius/reader/others_reader.py

- When opening a NIfTI file it checks whether there are multiple volumes, and if more than 1 exist, open a dialog allowing the user to select which volume should be opened.
- Raise a warning dialog when pixel value rescaling is applied. This is applied when pixels have too small values (e.g., 0-1) and converting to integer binarize the image. Now it scales it to 0-255 and warns the user.

FIX: Fail to import NIfTI with multiple volumes

---

invesalius/gui/task_navigator.py

After Refine dialog, in task_navigator it was calling a non-existing UpdateUI method and raised an error.

FIX: Refine called non-existing UpdateGUI

---

invesalius/data/slice_.py
invesalius/gui/data_notebook.py
invesalius/gui/dialogs.py
invesalius/gui/task_navigator.py
invesalius/gui/task_surface.py

- Added a delete option to the marker list context menu
- Added context menu to the mask list in the Data panel with options to change color, duplicate, and delete the selected mask
- Added context menu to the surface list in the Data panel with options to duplicate, delete, and change the color and transparency of the selected surface

Context menu improvements

---

invesalius/constants.py
invesalius/gui/dialogs.py
invesalius/gui/frame.py
invesalius/gui/preferences.py
invesalius/gui/task_navigator.py
invesalius/gui/widgets/fiducial_buttons.py
invesalius/net/pedal_connection.py

New class for creating fiducial buttons and keeping track of which button to set next: used to reimplement fiducial buttons for object and tracker.
Object fiducials:
- Register fiducials with a single click
- Colored buttons
Tracker fiducials:
- Changed fiducial registration order to left ear, nasion, right ear.
- Allow changing default fiducial registration order through constants.py.
- Allow setting fiducials outside default order.
- Improved code structure.

Improved object and tracker fiducial registration UI

---

invesalius/control.py
invesalius/gui/dialogs.py

This pull request introduces significant improvements to the File/Save Project functionality by replacing the busy cursor with a dynamic progress bar dialog. The progress bar dialog provides users with informative feedback on the status of the save operation, enhancing the overall user experience.
Solving part of this issue #707 
- **Added `ProgressBarHandler` Class:** 
- Implemented a new class called `ProgressBarHandler`, which inherits from `wx.ProgressDialog`.
- This class encapsulates the functionality of the progress bar dialog.
- **Implemented Functions:**
- `wasCancelled`: Checks whether the progress dialog was cancelled by the user.
- `update`: Updates the progress dialog with the current progress value.
- `close`: Closes the progress dialog.
- `pulse`: Provides visual feedback …

Add Progress bar for File/Save Project functionality , replacing busy cursor

---

invesalius/gui/widgets/clut_imagedata.py
invesalius/gui/widgets/clut_raycasting.py

- 📌 **changes Summary**
- removed `slots=True` from `Node` dataclass in `invesalius/gui/widgets/clut_imagedata.py`.
- removed `numpy.floating[Any]` from `invesalius/gui/widgets/clut_raycasting.py`
- 🐞 **Bug Fixes**:
- Restored Python 3.8 compatibility.

removed slots and numpy.floating

---

invesalius/project.py

It's not possible to launch new instance of invesalius because `image_fiducials` is a numpy array. So this PR converts `image_fiducials` to list.

Fix launch new instance of InVesalius

---

invesalius/gui/frame.py

This pull request addresses issue [https://github.com/invesalius/invesalius3/issues/789](url) by updating the "Getting Started" link in the Help menu. The previous link pointed to an outdated PDF manual. Now, clicking "Getting Started" will open the new user manual available at [https://invesalius.github.io/docs/user_guide/user_guide.html](https://github.com/invesalius/invesalius3/pull/url)
**Changes made:**
Updated the URL in the frame.py file to point to the new user manual.
**Testing:**
Verified that the Help > Getting started link opens the new user manual in the default web browser.
Hi @henrikkauppi @vhosouza @tfmoraes please review this new PR.

Update "Getting Started" link to the new user manual

---

invesalius/reader/dicom.py

In `dicom.py` it was using `eval` which is unsafe.

Removed eval from dicom.py

---

invesalius/gui/frame.py

This pull request addresses issue [https://github.com/invesalius/invesalius3/issues/789](https://github.com/invesalius/invesalius3/pull/url) by updating the "Getting Started" link in the Help menu. The previous link pointed to an outdated PDF manual. Now, clicking "Getting Started" will open the new user manual available at [https://invesalius.github.io/docs/user_guide/user_guide.html](https://github.com/invesalius/invesalius3/pull/url). It always link to the newest documentation regardless of the selected language?
**Changes made:**
Updated the URL in the frame.py file to point to the new user manual.
Hi @henrikkauppi @vhosouza @tfmoraes  please review this new PR.

Update "Getting Started" always link to new documentation

---

invesalius/gui/frame.py
invesalius/gui/task_navigator.py

This PR fixes issue https://github.com/invesalius/invesalius3/issues/790, which involves the incorrect positioning of the fiducial buttons for the Left Ear and Right Ear in the coregistration Image and Patient tabs. Previously, the buttons were incorrectly placed, with the Left Ear button on the right side and the Right Ear button on the left side. This update switches their positions to correctly match the top-down view of the head.
Changes Made:
Updated the task_navigator.py file.
Testing:
Verified that the Left Ear and Right Ear buttons are now correctly positioned in the Image tab.
Verified that the Left Ear and Right Ear buttons are now correctly positioned in the Patient tab.
Hi @henrikkauppi @vhosouza @tfmoraes please review this new Pull request.

Fix coregistration fiducial button positions

---

invesalius/data/coordinates.py
invesalius/data/imagedata_utils.py
invesalius/data/tractography.py
invesalius/data/transformations.py
invesalius/gui/deep_learning_seg_dialog.py
invesalius/gui/dialogs.py
invesalius/segmentation/deep_learning/segment.py

Ruff:
np.mat -> numpy.asmatrix
np.Inf -> numpy.inf
np.float_ -> numpy.float64
Manual:
Replace legacy `np.random.random` call with `np.random.Generator`
Replace legacy `np.random.rand` call with `np.random.Generator`
Replace legacy `np.random.uniform` call with `np.random.Generator`
Replace legacy `np.random.normal` call with `np.random.Generator`

Use ruff and manual coding to adapt to numpy 2

---

invesalius/gui/preferences.py

The bug occurs when changing the tracker, after which preferences cannot be closed normally (pressing OK will cause a wx error and preferences won't close). 
You'll see preferences is re-opened (hidden and shown again) when the tracker is changed. This behavior is probably the cause of the bug... 
This commit is a quick fix that ignores the source of the bug

Quick fix for a bug in preferences.py

---

invesalius/gui/default_viewers.py

- Automatically maximize the volume viewer when navigation is started
- Fix the issue where the volume viewer gets stuck in the maximized state and it can't be restored to the original state
Fixes #835

FIX: maximize volume viewer when starting navigation

---

invesalius/gui/preferences.py

FIX: Error when trying to open Preferences

---

invesalius/project.py

For older python version, like 3.8.0, tarfile.OutsideDestinationError is not available, and raises errors.
tarfile.TarError is more general.

FIX: change tarfile exception for back compatibility

---

invesalius/data/markers/surface_geometry.py
invesalius/gui/dialogs.py

The smooth surface is used for creating targets for robot positioning. This smoothing method corrects small segmentation deformations, closes holes, and slightly inflates the smooth surface. The inflation is crucial for the safety of the robot's target, ensuring that the coil target is slightly away (in the millimeter range) from the scalp. This separation allows the force and torque control to perform better.

Fix smooth surface for target creation

---

invesalius/navigation/iterativeclosestpoint.py
invesalius/navigation/tracker.py
invesalius/pubsub/pub.py

Added type annotations to a couple of files from navigation module, addressing issue #497:
- Enhanced `navigation/tracker.py` and `navigation/iterativeclosestpoint.py` with return type annotations
- Fixed missing method signature type hints
- Validated with strict mypy flags and ruff checks
To verify the updates, I ran the following `mypy` command:
```bash
mypy invesalius/navigation/tracker.py invesalius/navigation/iterativeclosestpoint.py \
--follow-imports=skip \
--disallow-untyped-defs \
--disallow-any-generics \
--disallow-incomplete-defs \
--warn-redundant-casts \
--warn-unused-ignores \
--no-implicit-optional \
--strict-equality \
--warn-return-any \
--warn-unused-configs
```
And the result was:
```plaintext
Success: no issues found in 2 source files
```
I'm excited about the …

Type Annotations for tracker.py and iterativeclosestpoint.py

---

invesalius/gui/task_navigator.py

- Standardizes the button layout across different tabs in the coregistration panel. Now the back and next-buttons are always in the same place across all tabs.
- Adds the missing back-button to the TMS coil tab.

MOD: standardize button layout across tabs in the coregistration panel

---

invesalius/gui/frame.py

This fixes issue #893 
To fix this:
- Explicitly skipped the events CTRL+S, CTRL+Shift+S, and CTRL+Q in ```OnGlobalKey``` function.
The shortcuts are now being properly being handled by ```OnMenuClick``` as intended.
Kindly review this PR @tfmoraes  @paulojamorim  @henrikkauppi  @rmatsuda

FIX: Shortcuts not responding

---

.github/workflows/bundles.yml
bundle_tools/win/app.spec
pyproject.toml

This PR updates the `bundles.yml` workflow file to use `uv` instead of `pip` for building windows executables. 
The key changes include:
- Replacing `setup.py` -based installation with `uv sync`
- Ensuring dependencies are installed from `pyproject.toml`
- Updating the build process to align with uv and scikit-build-core
- Updates Python version to 3.12
- Reason :In Python versions below 3.12, `pip install -e .` does not function properly, causing installation issues. 
- Python versions above 3.12 do not have support for `pyacvd` yet.
@tfmoraes @paulojamorim Could you please review this PR. Thanks!

Migrate `bundles.yml` GitHub Action to Use `uv` instead of  `pip`

---

invesalius/data/slice_.py
invesalius/data/surface.py
invesalius/gui/task_tractography.py
invesalius/navigation/iterativeclosestpoint.py
invesalius/navigation/navigation.py
invesalius/navigation/tracker.py

I found the same affine transformation code duplicated in 4 different places across the codebase and decided to clean it up. This PR addresses the TODO comment in `navigation.py` that highlighted this issue:
> "TODO: This affine and affine_vtk are created 4 times. To improve, create a new affine object inside Slice() that contains the transformation with the img_shift."
I created a new method `get_world_to_invesalius_vtk_affine()` in the `Slice` class that centralizes this functionality and replaced all the duplicate code with calls to this method. The duplicated code was in:
- `surface.py`
- `task_tractography.py` (twice)
- `navigation.py`
The new method:
- Works with both regular and inverse transformations
- Falls back to different data sources if needed
- Has proper type annotations …

Persistent Affine Refactor

---

invesalius/gui/frame.py

FIX:The application terminates if you cancel the confirmation dialog box for exit.

---

invesalius/data/slice_.py
invesalius/data/viewer_volume.py

- Fixes #936 
3D slice widgets start at the correct position

fix: 3D slice widgets now are enabled in the correct position

---

.github/workflows/pre-commit.yml

This pull request updates the GitHub Actions workflow configuration for pre-commit checks. The main changes involve upgrading the versions of the actions used.
This PR is in response to https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts
Workflow configuration updates:
* [`.github/workflows/pre-commit.yml`](diffhunk://#diff-ac5eead3f3ce4863c524fff031a87b7aecccb4a0493df087a4e1c704a1505036L8-R17): Updated `actions/checkout` from version 2 to version 4.
* [`.github/workflows/pre-commit.yml`](diffhunk://#diff-ac5eead3f3ce4863c524fff031a87b7aecccb4a0493df087a4e1c704a1505036L8-R17): Updated `actions/setup-python` from version 2 to version 5.
* [`.github/workflows/pre-commit.yml`](diffhunk://#diff-ac5eead3f3c …

FIX: pre-commit.yml in response to up coming github changes

---

.github/workflows/cache.yml

This pull request optimizes the GitHub Actions cache workflow to reduce CI runtime by avoiding unnecessary Ubuntu dependency installation when the Python dependency cache is already present.
This cuts down cache check time by 50%

OPTIMIZE: cache.yml by 1min

---

invesalius/gui/frame.py

This pull request includes changes to the `invesalius/gui/frame.py` file to simplify the `ExitDialog` method by removing platform-specific code for macOS.
Simplification of `ExitDialog` method:
* [`invesalius/gui/frame.py`](diffhunk://#diff-010bd7ee7abcf4486d91a94c10b30ecd5f38a414f2bff3ec760f0829551717eeL515-L520): Removed the conditional logic that handled macOS-specific dialog creation, simplifying the method to use a single dialog creation process for all platforms.
before:
after:

refactor: simplify ExitDialog implementation 

---

invesalius/data/surface.py
invesalius/gui/task_navigator.py

This pull request includes a change to the `OnLargestSurface` method in the `invesalius/data/surface.py` file. The change improves error handling by checking if the surface index exists in the `surface_dict` before proceeding. Currently, the system hangs if this problem is encountered.
Recreate error:
1. Start app
2. Import DICOM image... ie. [`Chest`](https://invesalius.github.io/download.html#:~:text=Download-,Chest,-Download)
3. Configure 3D surface -> Advanced options -> Select largest surface
Error handling improvement:
* [`invesalius/data/surface.py`](diffhunk://#diff-ac4948ccf9066c0269d0546990162180fcdf44aeaa22abe91501b20eaae1ae69R338-L341): Added a check to ensure the `last_surface_index` exists in `proj.surface_dict` before attempting to access it, and prints an error message if …

fix: handle missing surface index in OnLargestSurface()

---

invesalius/gui/frame.py

Please review sir @paulojamorim @rmatsuda and let me know about further changes
This PR addresses issue:
-  #957 
by fixing a KeyError that occurs when accessing the preferences dialog. The error was caused by missing keys in the values dictionary returned from the preferences dialog.
The fix uses the `.get()` method with default values for all logging-related parameters, preventing the KeyError when a key is not present in the dictionary.
The changes are focused solely on fixing this specific issue, with no additional modifications to other functionality.
Thank you sir for the constant support.

Fix KeyError in preferences dialog for logging settings (issue fix #957)

---

invesalius/gui/deep_learning_seg_dialog.py

Fixes #975 
Made a small fix to properly update and show the progress bar after `Segment` is clicked by adding `self.Update()` at the end of `ShowProgress()`

Fix: UI glitch before progress bar starts in Brain Segmentation dialog 

---

invesalius/gui/dialogs.py

Fixes an AttributeError that occurs when using the scanner coordinate navigation dialog. The error happens because the `result` attribute is accessed in SetNewFocalPoint `(edit > go to slice / go to scanner coord..)` before it's initialized.✅
⛑️Changes:
- Initialize `result` attribute to None in _init_gui method
- Add null check before using result in SetNewFocalPoint
This prevents the "AttributeError: 'GoToDialogScannerCoord' object has no attribute 'result'" error while maintaining the existing functionality.

[ Fix ]  AttributeError in GoToDialogScannerCoord scanner coordinate navigation

---

invesalius/gui/task_navigator.py

Fix issue #986. When importing a NIfTI file or loading a project, the view automatically switches to the head model page. Fix the issue when the import is canceled.
- Pending: The automatic switch is not yet implemented for DICOM imports.
- TODO: Apply the same automatic page switch for DICOM imports.
- Note: Not urgent, as NIfTI is the primary format used in NeuroNav.

FIX: verify project status before "Move to head model page"

---

tests/test_segmentation_tools.py

- `test_do_watershed()`: Tests watershed segmentation with memory-mapped files.
- `test_edit_mask_pixel_orientations()`: Tests brush application across all orientations.
- `test_edit_mask_pixel_boundaries()`: Tests boundary conditions.
- `test_edit_mask_pixel_operation_values()`: Tests different fill values.

Extended segmentation tests with Watershed

---

.pre-commit-config.yaml
invesalius/data/volume.py
invesalius/data/volume_mask.py

- Closes #1017 
Fast fix adding the missing imports.
I went looking in the pre-commit because of this bug and it seems quite out-dated (and only capturing import order or formatting). I think linting errors are more important and should be there as well.

fix: add missing imports to `volume_mask.py`

---

invesalius/data/styles_3d.py
invesalius/data/viewer_volume.py
invesalius/data/visualization/coil_visualizer.py

This PR introduces fixes and improvements related to navigation and rendering behavior.
FIX: Always show vector_field_assembly regardless of state.
FIX: Hide the pointer during targeting only if navigation is active.
ENH: Ignore user interactions on 3D views, which may improve navigation performance.

Fix minor navigation bugs
