- invesalius/data/surface.py
- invesalius/gui/data_notebook.py
Now InVesalius shows surface area in the data notebook
> Surface area

- invesalius/data/converters.py
- invesalius/data/measures.py
- invesalius/data/slice_data.py
- invesalius/data/styles.py
- invesalius/data/viewer_slice.py
- invesalius/gui/data_notebook.py
- invesalius/project.py
Add a canvas to draw over the Slice Viewer. This canvas is able to draw geometric forms, unicode text and has support to RGBA. Also, this adapts the measurement system to show the measurements using this canvas system.
> Measure canvas

- invesalius/data/measures.py
- invesalius/data/viewer_slice.py
Now the Canvas does not have direct access to the measurements, it is responsibility of the viewer to add to the canvas what it needs to render.
> Canvas reeng

- invesalius/control.py
- invesalius/data/converters.py
- invesalius/data/imagedata_utils.py
- invesalius/data/styles.py
- invesalius/gui/bitmap_preview_panel.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
- invesalius/gui/import_bitmap_panel.py
- invesalius/reader/bitmap_reader.py
Improvements of micro-ct import files.
- Remove slice functionality
- Bug fixes
> Micro ct improvements

- invesalius/gui/bitmap_preview_panel.py
- invesalius/gui/dialogs.py
- invesalius/gui/import_bitmap_panel.py
- invesalius/reader/bitmap_reader.py
Enhancements:
- Add support to shift key to select a range of bitmaps in import bitmap (uCT).
- Add support to ctrl key to select sparse  bitmaps in import bitmap (uCT).
- Removed unused code.
- Design improvements in import bitmap dialog.
> Micro ct shift delete

- invesalius/data/styles.py
- invesalius/gui/dialogs.py
Improved the dialog interface used to config the fill holes and remove parts. Also, when using 3D connectivity, it show a progressdialog.
> Gui improvements to Fill holes and remove parts

- invesalius/data/styles.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
Close button on remove parts, fill holes and region growing segmentation.
Cancel and Ok button on the select parts.
> Improvements to GUI of FFill tools

- invesalius/data/styles.py
- invesalius/gui/dialogs.py
Adds to InVesalius another region growing segmentation tool: confidence.
> Add Region growing confidence segmentation tool

- .gitignore
- invesalius/data/cy_mesh.pyx
- invesalius/data/cy_my_types.pxd
- invesalius/data/surface.py
- invesalius/gui/dialogs.py
- setup.py
Implements ca smoothing in Cython
> Casmoothing implemented in cython

- invesalius/data/surface.py
- invesalius/gui/data_notebook.py
- invesalius/gui/dialogs.py
This pull request gives invesalius the possibility to import mesh files (STL, PLY, OBJ and VTP) into a project.
> Import mesh

- invesalius/constants.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
- invesalius/gui/task_navigator.py
Navigation update 
-Markers file extension update and transifex conflicts solved
-Disable mask when navigation starts
-Enable cross when navigation starts if cross is disabled
-Shows msg in statusbar when a tracker is connecting
> Navigation update 

- invesalius/data/coordinates.py
- invesalius/data/trackers.py
- invesalius/gui/frame.py
- invesalius/gui/task_navigator.py
- Remove tracker when invesalius is closed
- Fixed polhemus connection warning
- Fixed claron tracker scale
- Added msg for statusbar when try to disconnect tracker
> Remove tracker when InVesalius is closed

- invesalius/data/coordinates.py
- invesalius/data/trackers.py
- invesalius/data/trigger.py
Fix polhemus tracker connection
> Fix trackers connection

- invesalius/data/trackers.py
Define reference and probe names
> Fix MTC sensors name

- invesalius/data/coordinates.py
- invesalius/data/trackers.py
- invesalius/data/trigger.py
- invesalius/data/viewer_volume.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
- invesalius/gui/task_navigator.py
- Show sensors ID in viewer volume
- Use PLH stylus button as a external trigger
- Dialog to confirm all markers deletion
> Navigation improvement

- invesalius/data/measures.py
- invesalius/data/slice_data.py
- invesalius/data/styles.py
- invesalius/data/viewer_slice.py
- invesalius/data/vtk_utils.py
Using Canvas to render text over the vtkrenderer
> Text canvas

- invesalius/gui/task_navigator.py
Fixed bug when no data is selected and it is tried to delete, after a deletion.
> Fixed 'remove marker' bug

- invesalius/data/coordinates.py
- invesalius/data/trackers.py
Fastrak works with wrapper connection.
> Support fastrak

- invesalius/data/interpolation.pxd
- invesalius/data/interpolation.pyx
- invesalius/data/slice_.py
- invesalius/data/transforms.pyx
- invesalius/gui/dialogs.py
Implements Lanczos to 3D interpolation and gives the user the option to set the used interpolation.
> Lanczos 3d

- invesalius/data/coordinates.py
- invesalius/data/trackers.py
Fixed: dynamic reference and unicode standard.
> Fix dynamic ref

- invesalius/data/trigger.py
Supports the use of PLH trigger in PCs without serial ports
> PLH stylus button can be used in PCs without serial ports

- invesalius/control.py
- invesalius/data/imagedata_utils.py
- invesalius/data/vtk_utils.py
- invesalius/gui/dicom_preview_panel.py
- invesalius/reader/dicom.py
- invesalius/reader/dicom_grouper.py
- invesalius/reader/dicom_reader.py
Open Multiframe dicom files. It uses the same dicom gui.
> Open Multiframe dicom

- invesalius/data/trigger.py
- invesalius/gui/task_navigator.py
Fixed show object, Patriot stylus trigger and marker deletation.
> Fixed pubsub for neuronavigation 

- invesalius/data/interpolation.pyx
- invesalius/data/surface.py
- invesalius/data/surface_process.py
- invesalius/gui/dialogs.py
- invesalius/utils.py
This pull request uses python multiprocessing pools to make the surface creation cancellable. Also shows a progress dialog to make it simple to the user monitor the surface creation and cancel it. Also, if a error happen a dialog will show the error with exception.
> Cancelable surface creation

- app.py
- invesalius/control.py
- invesalius/data/surface.py
- invesalius/gui/dialogs.py
- invesalius/gui/preferences.py
- invesalius/gui/task_exporter.py
- invesalius/session.py
- invesalius/utils.py
Session now behaves as a dict. Also allows to creates new sessions and keys inside Session. Its very useful, for instance, to save the last folder used to open or export something from InVesalius. Or creates a new option more easily. Now sessions is saved using JSON format.
> Session as dict

- invesalius/constants.py
- invesalius/data/viewer_slice.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
Adds to the user the possibility of go to a slice typing the slice number
> Go to slice dialog tool

- invesalius/constants.py
- invesalius/control.py
- invesalius/data/surface.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
- invesalius/gui/task_navigator.py
Created a dialog to entry physical world coordinates to be transformed to invesalius coordinate system.
-Functionality works with new invesalius projects
-Automatically show intersection crosses
-Disable dialog if images has no affine matrix 
-Disable dialog if old inv project
> Dialog "go to" scanner coordinate system 

- invesalius/control.py
- invesalius/data/converters.py
- invesalius/data/imagedata_utils.py
- invesalius/gui/bitmap_preview_panel.py
- invesalius/gui/dicom_preview_panel.py
- invesalius/reader/dicom.py
- invesalius/reader/dicom_reader.py
Remove VTKGDCM as dependency, just use GDCM directly.
> Remove vtkgdcm

- invesalius/data/trackers.py
- invesalius/data/trigger.py
- Better errors messages for polhemus tracker
- Trigger message enhanced
> Minor enh nav

- invesalius/data/converters.py
- invesalius/data/imagedata_utils.py
- invesalius/data/slice_.py
- invesalius/gui/import_panel.py
- invesalius/reader/bitmap_reader.py
Import single slice DICOM and BMP.
> Single slice import

- invesalius/data/viewer_volume.py
- invesalius/gui/dialogs.py
- invesalius/gui/task_navigator.py
create polydata from the imported stl
> Update imported stl for navigation

- app.py
> changed iterator access

- app.py
- invesalius/data/viewer_slice.py
- invesalius/gui/brain_seg_dialog.py
- invesalius/gui/data_notebook.py
- invesalius/gui/default_viewers.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
- invesalius/gui/preferences.py
- invesalius/gui/task_navigator.py
- invesalius/gui/task_slice.py
- invesalius/gui/task_surface.py
- invesalius/gui/widgets/slice_menu.py
- FIx sizer error to make InVesalius work with wxPython 4.1
- Not using Mixin with ListCtrl to make edition and check image
- Force X11 in Linux (wxPython with OpenGL not working in Wayland)
> wxpython 4.1 and remove mixin from ListCtrl

- app.py
> FIX: Locale problem crashing with Windows 10 and certain locales

- invesalius/gui/task_navigator.py
- It had broken due to a mix-up between fiducial name ("LE") and label ("LEI"). Fix by doing the mapping from label (which is
stored on disk) to name before triggering 'Set image fiducial' event.
> FIX: Loading image fiducials from disk

- invesalius/gui/task_navigator.py
Essentially, start/stop navigation using "Start navigation" and "Stop navigation" events.
> MOD: Decouple navigation starting/stopping from the UI

- invesalius/data/vtk_utils.py
- invesalius/gui/dialogs.py
- invesalius/gui/task_navigator.py
- Gets coordinates from probe instead 'Set cross focal point'
- Creates a new thread to process ICP
- Show the number of poses recorded
> Navigation ICP coregistration improvements

- app.py
- invesalius/gui/task_navigator.py
- invesalius/net/pedal_connection.py
- optional-requirements.txt
- requirements.txt
- Show the pedal status in a checkbox in the UI. Add actual
functions for the pedal later.
- For now, hide the feature behind a feature-flag (--use-pedal)
> ADD: Optional use of trigger pedal

- invesalius/constants.py
- invesalius/data/coregistration.py
- invesalius/gui/task_navigator.py
- Some steps towards decoupling GUI and domain logic, namely, by adding
classes Navigation and Tracker, which take some of the responsibility
previously handled by NeuronavigationPanel.
- This is done to prepare to do some changes in the GUI, such as
moving "Navigate" button elsewhere -- previously, it was hard
to do due to the elements in the GUI being tightly coupled with the
implementation of navigation.
- Also some other minor clean-up and style improvements, such as
using more consistent and more descriptive variable names
> MOD: Refactor task_navigator.py

- invesalius/gui/dialogs.py
- invesalius/gui/task_navigator.py
-ENH: stop navigation to perform ICP
-FIX: remove ICP thread to avoid vtk freezing
-FIX: popup error when tracker is not connect
> MOD: Refactored ICP to their own class

- invesalius/gui/task_navigator.py
Based on @vhosouza's comments on my previous PR (#302).
> MOD: Minor changes to function names in task_navigator.py

- invesalius/control.py
- invesalius/data/imagedata_utils.py
- invesalius/data/surface.py
- invesalius/data/viewer_volume.py
- invesalius/gui/data_notebook.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
- invesalius/project.py
- Removed unused functions and code
--
This is @vhosouza's work -- I only resolved the merge conflict and created the PR.
> FIX: Fixed the transformation when surface mesh is on scanner coordinate system

- invesalius/data/trigger.py
Change originally courtesy of @vhosouza.
> MOD: Remove commented out code in trigger.py

- invesalius/data/viewer_volume.py
Change originally courtesy of @vhosouza.
> MOD: Minor clean-up of viewer_volume.py

- invesalius/data/viewer_volume.py
Change originally courtesy of @vhosouza.
> MOD: Change new marker radius to 1.5 and opacity to 1

- invesalius/constants.py
- invesalius/gui/task_navigator.py
Change originally courtesy of vhosouza.
> MOD: Move wildcard constant for marker files to constants.py

- invesalius/data/trackers.py
- invesalius/gui/dialogs.py
- invesalius/inv_paths.py
Add dialog window for selecting the calibration file and user profile file for optitrack system
> Add dialog window for inputing optitrack directory files

- invesalius/gui/task_navigator.py
- New mkss file format with better structure
- Create, save, load markers updated
The changes mostly courtesy of @vhosouza; I rebased them on top
of the current main branch and did a few further changes.
> UPD: Refactor markers in navigation

- invesalius/data/serial_port_connection.py
- invesalius/gui/task_navigator.py
- Do more specific error handling in SerialPortConnection class,
distinguishing between the error caused by the queue becoming full
from the error caused by reading from or writing into the serial port.
- Also, add a comment explaining why additional sleeping is needed inside
the thread in SerialPortConnection class.
> ADD: Send pulse via serial port when pedal triggered and coil at target

- invesalius/constants.py
- invesalius/gui/task_navigator.py
1. mkss files now have a magick string and a version number at the beginning of the file
2. mks files are supported as legacy, the code for handling mks files isolated (to be removed in the future?)
3. strings in the mkss files are now are quoted
> Added versioning to markers file format

- invesalius/data/bases.py
- invesalius/data/coordinates.py
- invesalius/data/coregistration.py
- invesalius/data/viewer_volume.py
- Add also its inverse function, which will be used in a later patch.
> CLP: Extract an own function for a common coordinate transformation

- .gitignore
Added VS Code project/workspace files to gitignore.
> Updated gitignore to ignore VSCode project setting files

- invesalius/gui/task_navigator.py
I did some cleanup of the markers' code. It should change no functionality.
> Cleanup of the markers code

- invesalius/data/imagedata_utils.py
- invesalius/gui/task_navigator.py
* When unable to compute the world coordinates (the 'affine' matrix
being missing from the project), output empty strings ("") as the
coordinates and the angles.
> MOD: Export world coordinates into marker file

- invesalius/data/viewer_volume.py
- invesalius/gui/task_navigator.py
-minor: set size to trackers combobox
> FIX: change marker colors

- invesalius/constants.py
- invesalius/data/viewer_volume.py
- invesalius/gui/task_navigator.py
- Added a new class for storing markers
- General marker code cleanup
- Marker's label decoupled from the target status
- Several bugfixes
> Marker code refactoring

- invesalius/data/viewer_volume.py
Deactivate coil projection when the target mode is activated
> Deactivate coil projection when target mode is activated

- invesalius/constants.py
- invesalius/data/elfin.py
- invesalius/navigation/robot.py
- reset motion when a new target is set
> ADD: Forces to stop the robot when some error occurs

- environment.yml
- invesalius/constants.py
- invesalius/control.py
- invesalius/data/coordinates.py
- invesalius/data/coregistration.py
- invesalius/data/styles.py
- invesalius/data/surface.py
- invesalius/data/tractography.py
- invesalius/data/viewer_volume.py
- invesalius/gui/dialogs.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/navigation.py
- Improved set of parameters for real time tractography
- Fixed the load of JSON configuration file for the tractography settings
> ENH: Update tractography parameters and fix config file load

- app.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/navigation.py
- invesalius/net/neuronavigation_api.py
See the description in neuronavigation_api.py for the details and purpose of this change.
> ADD: NeuronavigationApi to send coil pose via connection object

- app.py
To enable starting InVesalius by importing app.py and calling main().
> Move initializations to main()

- invesalius/data/styles.py
- invesalius/data/styles_3d.py
- invesalius/data/viewer_slice.py
- invesalius/data/viewer_volume.py
- invesalius/data/vtk_utils.py
- invesalius/gui/widgets/canvas_renderer.py
VTK on wxPython running on Mac M1 returns the mouse position the half of actual value. It's happening because of this https://docs.wxpython.org/wx.glcanvas.GLCanvas.html (third paragraph)..
> Mac M1 HighDPI display

- invesalius/data/viewer_volume.py
- invesalius/gui/task_navigator.py
- Fix the marker id in viewer volume. 
- Enable "Set target" option only when orientation is not none
> Fix arrows markers

- invesalius/data/brainmesh_handler.py
- invesalius/gui/task_navigator.py
- Use affine matrix to transform brain mesh peel from file
- Fixed brain mesh AP flip.
> FIX: brain mesh peel from file

- invesalius/gui/task_navigator.py
> FIX: initialization of current_coord

- invesalius/gui/task_navigator.py
- invesalius/net/neuronavigation_api.py
@tfmoraes: After #413 was merged, this can now be reviewed. Thanks!
> ADD: Send coil mesh using NeuronavigationApi

- invesalius/net/neuronavigation_api.py
Checks if the API connection exists for the coil mesh update
> FIX: check coil mesh connection

- invesalius/data/viewer_volume.py
- invesalius/gui/default_viewers.py
- invesalius/gui/task_navigator.py
If a marker is set as a target, shows an option to remove the target without removing the marker
> ADD: option to remove target without removing the marker

- invesalius/gui/default_viewers.py
- invesalius/gui/task_navigator.py
-ADD: disable camera checkbox during target mode
> FIX: sets volume camera false when target mode is on

- invesalius/gui/task_navigator.py
Fix is originally courtesy of Victor, I'm pushing it because I didn't find it merged to the current main.
> FIX: Parameters of OnActivateTargetMode function

- invesalius/data/trackers.py
This is following the previous pull request
> Modify importing polaris wrapper when is not windows system

- invesalius/data/trackers.py
Fix is originally courtesy of Victor, I'm pushing it because I didn't find it merged to the current main.
> FIX: Initialization of Polaris tracker

- app.py
- invesalius/data/e_field.py
- invesalius/data/viewer_volume.py
- invesalius/gui/dialogs.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/navigation.py
- invesalius/session.py
Remove for loops when filling color array for e-field visualization
Remove unnecessary comments
> Enhance efield visualization

- invesalius/constants.py
- invesalius/data/bases.py
- invesalius/data/viewer_volume.py
- invesalius/data/vtk_utils.py
- invesalius/gui/default_viewers.py
- invesalius/gui/dialogs.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/navigation.py
- Object navigation loader checks if obj path exits
- navigation target is updated to the last object created or loaded
> FIX: object navigation load

- invesalius/data/brainmesh_handler.py
- invesalius/data/viewer_volume.py
add polydatanormals for visualization of e-field actor
> Fix: Visualization of efield mesh

- invesalius/data/slice_.py
- invesalius/data/viewer_slice.py
- invesalius/data/volume.py
- invesalius/data/vtk_utils.py
- invesalius/gui/deep_learning_seg_dialog.py
- invesalius/gui/widgets/clut_raycasting.py
- invesalius/presets.py
This pull request updates the code to use Python's built-in `max()` function instead of an `if` statement to check the maximum of two values. This results in more straightforward, more efficient, and more readable code.
> Maximize Efficiency: Use max()

- invesalius/data/brainmesh_handler.py
- invesalius/data/viewer_volume.py
- invesalius/navigation/navigation.py
-Modify Efield LUT table creation for fix max min values and computed only once when initializing the Efield
-Update the vtkPolydataNormals only when visualizing E-field , this done thanks to @tfmoraes
> E field improvements

- invesalius/control.py
- invesalius/data/viewer_slice.py
- invesalius/data/viewer_volume.py
- invesalius/gui/data_notebook.py
- invesalius/gui/dialogs.py
- invesalius/gui/frame.py
- invesalius/gui/task_navigator.py
- invesalius/gui/task_tools.py
- invesalius/gui/widgets/gradient.py
- invesalius/net/utils.py
- invesalius/plugins.py
- invesalius/utils.py
Found few unused imports and have removed them. Solving unused imports in #546
> Removing unused import

- invesalius/gui/task_navigator.py
- invesalius/net/neuronavigation_api.py
Modify some names of functions and variables of e-field for better code readability
> Refactor efield neuronavigation

- invesalius/constants.py
- invesalius/gui/dialogs.py
ADD: constants NDI_IP
ENH: enable the user to manually input the IP or the camera ID
> Append NDI cameras IP to COM ports combobox

- invesalius/constants.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/robot.py
The robot connection was not properly working with recovering after crash feature.
> Fix robot recover after crash

- invesalius/data/tractography.py
The tractography was not working without loading the ACT.
I was missing the coord_offset_w for the tracts_queue.
> FIX: ComputeTractsThread was not computing coord_offset_w 

- invesalius/constants.py
- invesalius/data/brainmesh_handler.py
- invesalius/data/e_field.py
- invesalius/data/surface.py
- invesalius/data/viewer_volume.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/navigation.py
Add save efield data 
Modify lut table range 
Add file paths when using second computer
> Add save efield

- invesalius/gui/frame.py
- invesalius/session.py
> Dialog with cancel option for exit

- invesalius/data/viewer_volume.py
The orientation of the efield vectors was incorrect.
Add publisher/subscriber for the recolor efield vector
> Fix vectors efield

- invesalius/data/brainmesh_handler.py
- invesalius/data/e_field.py
- invesalius/data/viewer_volume.py
- invesalius/gui/task_navigator.py
- invesalius/net/neuronavigation_api.py
-Modify efield service, only gets vector from the maximum field.
-Add computation efield using multicoil set
-Modify saving data, only saves the maximum vector
> Efield minor modifications

- invesalius/constants.py
- invesalius/data/brainmesh_handler.py
- invesalius/data/e_field.py
- invesalius/data/surface.py
- invesalius/data/viewer_volume.py
- invesalius/gui/task_efield.py
- invesalius/gui/task_navigator.py
- invesalius/net/neuronavigation_api.py
-Fix error in coil rotation
-Add Color Range showing max min Efield magnitude
-Add input for dI/dt for coils
-Add calculation of the center of gravity for showing Efield vector
> Efield corrections and additions

- invesalius/gui/task_navigator.py
This applies the same fix as in PR #649 but to the new UI.
> FIX: Applies fiducial marker saving in state fiee to new navigation UI

- invesalius/constants.py
- invesalius/data/viewer_volume.py
-Create edges within thresholds in efield data.
> Create edges for efield

- invesalius/data/viewer_volume.py
- invesalius/gui/task_navigator.py
Optimized CreateMarker() in MarkersPanel to load thousands of markers faster. 
Optimizations:
- Markers added to ListCtrl with .Append() instead of .InsertItem().
- Volume viewer rendered once for all markers, instead of for each marker.
- ListCtrl hidden while adding markers.
> ENH: Faster loading markers from file

- invesalius/gui/task_navigator.py
- invesalius/navigation/image.py
- invesalius/project.py
Save image fiducials in project instead of state.
Refactored code updating ImagePage UI element data in task_navigator.py.
Fix RefinePage visual bug.
> MOD: Save image fiducials in project

- invesalius/constants.py
- invesalius/data/brainmesh_handler.py
- invesalius/data/surface.py
- invesalius/data/viewer_volume.py
- invesalius/gui/task_efield.py
- invesalius/gui/task_navigator.py
- optional-requirements.txt
-Add efield neuronavigation tools
-Changes to markers file
Not to be merged yet
> Efield modifications and improvements

- invesalius/gui/task_fmrisupport.py
- invesalius/gui/task_imports.py
- invesalius/gui/widgets/gradient.py
Work for Google summer of code (GSOC).
Summary of addition:
Processing fMRI volumes (Task/Rest/Films all types included)
Generating Displayable volumes for brain connectivity indications
Widgets / Options to load Displayable volumes for visualization with various colormaps at disposition![gsoc_res]
> ADD: fmri support tab + warning when wrong load + support various mod

- .gitignore
- invesalius/gui/task_fmrisupport.py
Fix the fMRI support, which is currently not working. Improve code quality and the distinction between method functionality.
> Fix fMRI support

- invesalius/navigation/image.py
Fiducials loaded from project by default and from state if session restored during startup.
Should fix #719.
> ENH: Saves image fiducials to state and project

- Dockerfile
- requirements.txt
- Changed dockerfile's Ubuntu version from 16.04 to 20.04
- Changed ordering in dockerfile and added pip upgrade and pip install to dockerfile
- Moved Ubuntu's python packages to requirements.txt
- Updated some python library versions
Command used to create container from image: `docker run -it --privileged --env="DISPLAY" --network=host --volume="$HOME/.Xauthority:/root/.Xauthority:rw" <image-name> bash`
Tested on Fedora 39 with X11 forwarding, no issues found
> Updated dockerfile

- invesalius/data/markers/marker.py
- invesalius/data/markers/marker_transformator.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/markers.py
- invesalius/navigation/navigation.py
- Store markers list and code used to add, remove, update markers etc. in a separate class in navigation/markers.py. Previously this code was all stored in MarkersPanel-class in task_navigator.py.
- Some code moved to single Marker class.
- New flow of control for markers functionality such that a new MarkersControl-class manages data, and is responsible for informing the views (GUI and volume viewer) about data updates. Previously, the MarkersPanel-class informed the viewer.
- Added NavigationHub-class to contain navigation related components. This class replaces up to 7 parameters passed around GUI classes in task_navigator.py before.
> Separate markers functionality from GUI

- docs/devel/example_closure.py
- print function missing parantheses at several places in the file
- Issue has been fixed
I have ran the repository locally to make sure that the change doesn't break the system
> Fix print parantheses

- invesalius/gui/task_navigator.py
- invesalius/navigation/markers.py
Added function call to load state such that the GUI updates properly when loading marker state.
Fixes #752
> HOTFIX: Markers not loaded to GUI from state on startup

- invesalius/data/markers/marker.py
- invesalius/gui/task_navigator.py
- invesalius/navigation/markers.py
The marker list can be sorted by column in either ascending or descending order by clicking the column header in the GUI.
> ADD: Sorting functionality to the marker list in GUI

- invesalius/data/coordinates.py
- invesalius/navigation/tracker.py
This reverts commit 6e62eab5f44f3efbf55f5342ab978f74819ed019.
The workaround seems to be unreliable, at least occasionally re-connecting repeatedly when first connecting to OptiTrack. Therefore, reverting for now.
> Revert "ADD: Reconnect to tracker if invalid coordinates received"

- .pre-commit-config.yaml
- README.md
- environment.yml
- optional-requirements.txt
- pyproject.toml
- 📌 **changes Summary**
- Added pre-commit to optional-requirements.txt.
- Wrote .pre-commit-config.yaml for ruff formatting and ruff import sorting.
- Added python3.8 badge for clearly indicating the currently supported python version. 
- ⚠️ **Breaking changes**
- None
- 🐞 **Bug Fixes**:
- None
1. pre-commit should work after installing it. Write the following commands if you don't have precommit.
Install using pip:
```console
pip install pre-commit
pre-commit install
```
Or Install using conda:
```console
conda install -c conda-forge pre-commit
pre-commit install
```
2. try making an empty commit using `git commit --allow-empty -m "testing". You should see a similar message to the following.
3. For running pre-commit against all files (formatting and ordering all imports). Run the …
> Precommit integration

- invesalius/gui/widgets/gradient.py
- invesalius/gui/widgets/inv_spinctrl.py
- invesalius/gui/widgets/slice_menu.py
- invesalius/utils.py
- 📌 **changes Summary**
- Closes #785.
- Formatted and Partially annotated `invesalius/utils.py`.
- Formatted `invesalius/gui/widgets/slice_menu.py`.
- Formatted and Added type information to `invesalius/gui/widgets/gradient.py` and `invesalius/gui/widgets/inv_spinctrl.py`.
- ⚠️ **Breaking changes**
- Changed API of `GradientDisp` and `GradientNoSlide` classes in `gradient.py` to be consistent with types. The main change is removing the attribute `self.colour` in `GradientNoSlide` and making the `__init__` initialize `self._gradient_colours` directly.
- 🐞 **Bug Fixes**:
- None
1. For testing type information using MyPy:
```console
mypy invesalius/gui/widgets/gradient.py invesalius/gui/widgets/inv_spinctrl.py --check-untyped-defs \
--disallow-any-generics --disallow-incomplete-defs …
```
> Type info Added to gradient.py and inv_spinctrl.py

- .github/workflows/pre-commit.yml
- 📌 **changes Summary**
- Added GitHub CI yaml file in `.github/workflows/pre-commit.yml` to run pre-commit on changed files.
- ⚠️ **Breaking changes**
- None
- 🐞 **Bug Fixes**:
- None
1. Making a test PR to a branch that has this workflow should activate the workflow. I have already tested it on a test-branch in my fork and it works for both positive and negative test cases.
> Added GitHub Actions for running pre-commit hooks on changed files in pull requests

- invesalius/gui/preferences.py
- invesalius/gui/task_navigator.py
Copy of Henrik's PR (https://github.com/invesalius/invesalius3/pull/831) with RUFF formating
- Rename start neuronavigation button as start navigation
- Remove unnecessary text about TMS coil new, load, and save buttons in 
- When clicking start patient registration while tracker is not selected, open tracker selection in preferences
> Small UI fixes

- invesalius/gui/frame.py
This PR is a quick fix for issue #834
> FIX: some keys were not working when changing mask, surface and measure labels 

- invesalius/constants.py
- invesalius/data/surface.py
- invesalius/data/visualization/mep_visualizer.py
- invesalius/gui/preferences.py
- invesalius/gui/task_navigator.py
- Fixed markers storage in the mep_visualizer
- Parameters optimized 
- Removed preload brain in config to avoid conflicts
> Fix and improvements brain motor mapping

- invesalius/gui/task_navigator.py
> MOD: always enable navigation tab

- invesalius/net/neuronavigation_api.py
Modify vector_field to swap x and y coordinates and adjust z orientation to match mTMS coil
> Fix mtms vector field

- pyproject.toml
- requirements.txt
- uv.lock
> Update requirements.txt with latest version of wxPython

- invesalius/navigation/image.py
- invesalius/navigation/markers.py
- pyproject.toml
Changes:
- Added type annotations to invesalius/navigation/image.py
- Added type annotations to invesalius/navigation/markers.py
- Tested using `mypy invesalius/navigation/image.py invesalius/navigation/markers.py`
- Set `ignore_missing_imports = true` for numpy modules in mypy config in pyproject.toml
Reason for changes:
Issue 497: Add type information to functions, methods and classes
> Type annotations for /navigation/image.py and /navigation/markers.py

- invesalius/utils.py
This PR improves the class TwoWaysDictionary by:
+ Removing redundant TypeError handling, as dict.pop(key) never raises a TypeError.
+ Handling only KeyError, which is the actual exception that occurs when a key is missing.
+ Adding a direct key existence check (if key in self) to avoid unnecessary exception handling.
> Proper exception handling in TwoWaysDictionary class.

- .github/workflows/bundles.yml
- bundle_tools/win/generate_installer.iss
- invesalius/__version__.py
- pyproject.toml
- uv.lock
https://github.com/Minionguyjpro/Inno-Setup-Action doesn't exists anymore. Calling Inno Setup (ISCC) using command line.
> Fix installer creation

- .github/workflows/bundles.yml
Just publishing the ai ready one.
> Fix nightly publish

- invesalius/data/imagedata_utils.py
- invesalius/data/polydata_utils.py
- invesalius/data/vtk_utils.py
- invesalius/error_handling.py
- invesalius/reader/dicom_grouper.py
- invesalius/reader/dicom_reader.py
This PR improves error handling across several modules in InVesalius:
- Implemented more robust error handling in `imagedata_utils.py`, `polydata_utils.py`, and `vtk_utils.py` to better manage VTK-related exceptions
- Enhanced error catching in `dicom_reader.py` and `dicom_grouper.py` to provide clearer feedback when DICOM files cannot be properly read or grouped
- Updated the central `error_handling.py` module with additional error types and handling capabilities
The log window now displays detailed, categorized error information with proper timestamps and context, making troubleshooting more straightforward when processing problematic files.
> Enhanced logging & error handling in data modules and DICOM reader

- invesalius/data/imagedata_utils.py
- invesalius/data/polydata_utils.py
- invesalius/data/vtk_utils.py
- invesalius/error_handling.py
- invesalius/reader/dicom_grouper.py
- invesalius/reader/dicom_reader.py
Reverts invesalius/invesalius3#964
> Revert "Enhanced logging & error handling in data modules and DICOM reader"

- .github/workflows/bundles.yml
Not create nightly release every push.
> Creating nightly release every 00:00 UTC time

- invesalius/gui/import_panel.py
When a user double-clicks on the "InVesalius Database" root item in the import panel, the application crashes with the following error: AttributeError: 'NoneType' object has no attribute 'GetGroups'
This PR adds validation checks to prevent crashes when clicking on items with no associated data. The fix ensures that only valid items can be double-clicked and processed.
- Added validation checks in `OnDblClickTextPanel` method to only process valid item data
- Enhanced the `LoadDicom` method with additional safeguards to prevent crashes with invalid groups
1. Load DICOM files from a directory
2. Double-click on the "InVesalius Database" root item - no crashes should occur
3. Verify normal double-clicking on patient and series items still works properly
> Fix crash when double-clicking InVesalius Database root item

- invesalius/gui/deep_learning_seg_dialog.py
FIX: Check if progressBar is IsBeingDeleted before updating it to prevent potential access errors or crashes during deletion.
> FIX: check if progress bar IsBeingDeleted before update

- invesalius/gui/frame.py
- invesalius/gui/interactive_shell.py
- invesalius/navigation/navigation.py
Everyone has its one preferred way of debugging things, but having an interactive shell within InVesalius helped me a lot, specially to understand the code base. I am making this PR from https://github.com/invesalius/invesalius3/pull/1006#issuecomment-3067427862.
Here is a small video of how it works:
https://github.com/user-attachments/assets/abe7a209-82fd-43ff-bfc6-577a93668bc9
> feat: add interactive python shell for debugging and testing purposes
